steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/haiti-food-price-monitor:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/haiti-food-price-monitor:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/haiti-food-price-monitor:$COMMIT_SHA]

  - name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/haiti-food-price-monitor:latest]

  - name: gcr.io/google.com/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - haiti-food-price-monitor
      - --image=gcr.io/$PROJECT_ID/haiti-food-price-monitor:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed

images:
  - gcr.io/$PROJECT_ID/haiti-food-price-monitor:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/haiti-food-price-monitor:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1800s
